/* Mejoras de jugabilidad y animacion para WORD SURVIVAL. */
(function(){
'use strict';
const ESCALA_JUGADOR=.68, ALTURA_OJOS=1.16;
function aplicarEscalaJugador(m){if(!m||!m.j||!m.j.modelo)return;m.j.modelo.scale.setScalar(ESCALA_JUGADOR);m.alturaCamara=ALTURA_OJOS;}
const iniciarOriginal=Motor.prototype.iniciar;
Motor.prototype.iniciar=function(){const r=iniciarOriginal.apply(this,arguments);aplicarEscalaJugador(this);return r;};
const actualizarCamaraOriginal=Motor.prototype._actualizarCamara;
Motor.prototype._actualizarCamara=function(){if(this.j)this.alturaCamara=ALTURA_OJOS;return actualizarCamaraOriginal.apply(this,arguments);};
Motor.prototype.golpearRecurso=function(){};
Motor.prototype.moverObjeto=function(){};
Motor.prototype.atacar=function(){if(this.criaturas&&this.j)this.criaturas.recibirDaño(2);};
function manoLibre(m,lado){return lado==='izquierda'?m.j.leftHand:m.j.rightHand;}
function ponerEnMano(m,obj,lado){const mano=manoLibre(m,lado);if(mano.userData.objetoSujeto)m.soltarDeMano(lado);const idx=m.objetosSuelo.indexOf(obj);if(idx>=0)m.objetosSuelo.splice(idx,1);if(obj.parent)obj.parent.remove(obj);mano.add(obj);obj.userData.objetoSujeto=true;obj.userData.manoSujeta=lado;obj.position.set(lado==='izquierda'?.03:-.03,-.22,-.18);obj.rotation.set(0,0,0);obj.scale.setScalar(1.15);mano.userData.objetoSujeto=obj;if(typeof m.mostrarMensaje==='function')m.mostrarMensaje('En mano '+(lado==='izquierda'?'izquierda':'derecha')+': '+(obj.userData.pickup?.name||'objeto'));}
Motor.prototype.soltarDeMano=function(lado){if(!this.j)return;const mano=manoLibre(this,lado),obj=mano.userData.objetoSujeto;if(!obj)return;mano.userData.objetoSujeto=null;obj.userData.objetoSujeto=false;obj.userData.manoSujeta=null;const p=mano.getWorldPosition(new THREE.Vector3());mano.remove(obj);if(obj.userData.pickup)this.crearObjeto(obj.userData.pickup.id,obj.userData.pickup.name,p.x,p.z,obj.userData.pickup.qty||1);};
function tomarObjeto(m,lado){const hit=m.encontrarHit();let o=hit&&hit.object;while(o&&!o.userData.pickup)o=o.parent;if(!o)o=m.objetosCercanos(2.4).sort((a,b)=>a.position.distanceTo(m.cam.position)-b.position.distanceTo(m.cam.position))[0];if(!o)return false;ponerEnMano(m,o,lado);return true;}
function recursoCompatible(obj,objetivo){if(!obj||!obj.userData?.pickup||!objetivo)return false;const id=obj.userData.pickup.id;if(objetivo.userData.arbol)return id==='hacha'||id==='pico_piedra'||id==='pico'||id==='hacha_piedra';return id==='pico_piedra'||id==='pico';}
function recolectar(m,lado){const mano=manoLibre(m,lado),obj=mano.userData.objetoSujeto;if(!obj||!obj.userData.pickup)return false;const objetivo=m.encontrarObjetivo();if(!objetivo||!recursoCompatible(obj,objetivo))return false;const recursos=objetivo.userData.recurso;if(!recursos)return false;m.soltarRecursos(recursos,objetivo.getWorldPosition(new THREE.Vector3()));if(objetivo.userData.arbol){objetivo.userData.vida=(objetivo.userData.vida||3)-1;if(objetivo.userData.vida<=0)m.mundo.derribarArbol(objetivo);}else if(objetivo.parent)objetivo.parent.remove(objetivo);return true;}
window.addEventListener('load',function(){const m=window.motor;if(!m||!m.renderer)return;m.renderer.domElement.addEventListener('mousedown',function(e){if(!m.j)return;const lado=e.button===0?'izquierda':e.button===2?'derecha':null;if(!lado)return;const objetivo=m.encontrarObjetivo(),mano=manoLibre(m,lado);if(objetivo&&mano.userData.objetoSujeto&&recursoCompatible(mano.userData.objetoSujeto,objetivo)){if(recolectar(m,lado)){m.j.animarMano(lado);return;}}if(tomarObjeto(m,lado))m.j.animarMano(lado);},true);});
const generarBase=Mundo.prototype.generar;
Mundo.prototype.generar=function(cx,cz){const r=generarBase.apply(this,arguments),chunk=this.chunks.get(`${cx},${cz}`);if(!chunk)return r;if(!chunk.hierbaAlta)chunk.hierbaAlta=[];if(!chunk.hierbaAlta.length){const mat=new THREE.MeshLambertMaterial({color:0x2f8f3a,side:THREE.DoubleSide,transparent:true,opacity:.9});for(let i=0;i<70;i++){const x=cx*this.tam+1+Math.random()*(this.tam-2),z=cz*this.tam+1+Math.random()*(this.tam-2),h=this.altura(x,z);if(this.tipoBloque(h)!=='cesped'||this.esAgua(x,z))continue;const g=new THREE.Group();for(let k=0;k<3;k++){const hoja=new THREE.Mesh(new THREE.PlaneGeometry(.13,1.05+Math.random()*.35),mat.clone());hoja.position.set((k-1)*.07,.5,0);hoja.rotation.y=k*Math.PI/3;hoja.castShadow=true;g.add(hoja);}g.position.set(x,h,z);g.userData.hierba=true;g.userData.fase=Math.random()*Math.PI*2;chunk.grupo.add(g);chunk.hierbaAlta.push(g);}}if(chunk.agua&&!chunk.agua.userData.olasNaturales){const agua=chunk.agua,originalCompile=agua.material.onBeforeCompile;agua.material.onBeforeCompile=function(shader,renderer){originalCompile.call(this,shader,renderer);shader.vertexShader=shader.vertexShader.replace('transformed.y += sin(position.x*.55 + waveTime)*.045 + cos(position.z*.42 + waveTime*.8)*.035;','transformed.y += sin(position.x*.55 + waveTime)*.10 + cos(position.z*.42 + waveTime*.8)*.075 + sin((position.x+position.z)*.25 + waveTime*1.35)*.055 + cos((position.x-position.z)*.18 - waveTime*.7)*.035;');};agua.userData.olasNaturales=true;agua.material.needsUpdate=true;}return r;};
const actualizarBase=Mundo.prototype.actualizar;
Mundo.prototype.actualizar=function(jx,jz,dt=.016){const r=actualizarBase.apply(this,arguments),t=performance.now()*.001;for(const chunk of this.chunks.values())if(chunk.hierbaAlta)for(const g of chunk.hierbaAlta){const a=Math.sin(t*1.7+g.userData.fase),b=Math.cos(t*1.15+g.userData.fase);g.rotation.z=a*.12;g.rotation.x=b*.07;}return r;};
const actualizarCriaturasBase=GestorCriaturas.prototype.actualizar;
GestorCriaturas.prototype.actualizar=function(dt){const r=actualizarCriaturasBase.apply(this,arguments);for(const c of this.lista){if(!c.modelo)continue;const t=c.faseAnimacion,movimiento=c.caminando?1:0;c.modelo.rotation.z=Math.sin(t*.55)*.018*movimiento;if(c.acuatico){c.modelo.rotation.x=Math.sin(t*.7)*.035;c.modelo.rotation.z=Math.sin(t*1.1)*.06;}else{const patas=c.modelo.userData.animacion?.patas;if(patas)for(let i=0;i<patas.length;i++)patas[i].rotation.z=Math.sin(t*.8+i*Math.PI)*.035;}}return r;};
const modeloAnimalBase=GestorCriaturas.prototype.modeloAnimal;
GestorCriaturas.prototype.modeloAnimal=function(tipo){const p=modeloAnimalBase.apply(this,arguments);if(!p)return p;const gris=this.mat(0x777777),piel=this.mat(0xc9a27a);if(tipo==='vaca'){const cola=new THREE.Group(),asta=new THREE.Mesh(new THREE.CylinderGeometry(.035,.06,.55,6),gris);asta.rotation.z=Math.PI/2;asta.position.x=-.28;cola.add(asta);cola.position.set(-1,1.15,0);p.add(cola);p.userData.colaNatural=cola;for(const z of [-.27,.27]){const oreja=new THREE.Mesh(new THREE.SphereGeometry(.14,8,6),piel);oreja.scale.set(.7,.45,1);oreja.position.set(.9,1.63,z);p.add(oreja);}}else if(tipo==='oveja'){for(const z of [-.32,.32]){const oreja=new THREE.Mesh(new THREE.SphereGeometry(.12,8,6),gris);oreja.scale.set(.65,.45,1);oreja.position.set(.92,1.42,z);p.add(oreja);}}else if(tipo==='pollo'){for(const z of [-.35,.35]){const ala=new THREE.Mesh(new THREE.SphereGeometry(.25,8,6),this.mat(0xe8e8e8));ala.scale.set(.55,.9,.28);ala.position.set(.05,.9,z);p.add(ala);}}return p;};
setInterval(function(){const m=window.motor;if(!m)return;if(m.j?.modelo)m.j.modelo.scale.setScalar(ESCALA_JUGADOR);if(m.criaturas)for(const c of m.criaturas.lista){const cola=c.modelo?.userData.colaNatural;if(cola)cola.rotation.y=Math.sin(performance.now()*.004+c.faseAnimacion)*.35;}},100);
})();
