/* WORD SURVIVAL ∞ - ESTILO POLIGONAL PROFUNDO */
(function(){
'use strict';
const PALETAS={
 terreno:['#3f7f35','#4e8d3d','#5b9845','#356b2d','#6aa34f','#78ae58'],tierra:['#6b452c','#7a5032','#8a5b38','#5c3b26','#956541','#a86d45'],piedra:['#666d73','#777e84','#858b90','#555b60','#92979b','#a4a8aa'],madera:['#70431f','#845128','#965f30','#603919','#a36d3d','#b8783d'],palo:['#a86b36','#bd7d42','#8e552a','#cb8c4c','#77451f','#d19355'],arena:['#c2a05b','#d0b16d','#b08e4d','#dec27f','#a8874a','#e4ca8a'],hojas:['#286d30','#347f38','#438c42','#205b28','#57964c','#6aa956'],agua:['#1b65a4','#277db8','#3d92c8','#15588f','#61b0d7','#7ac8e1'],humano:['#9a6045','#b97655','#c98662','#8a513d','#d3936c','#e0a07b'],vaca:['#eee9dc','#d9d0bd','#8a5b3d','#5b4638','#f5f1e7','#bca98e'],oveja:['#eeeae0','#d8d3c8','#c2bcb0','#f5f2e9','#77716a','#b8b2a7'],pollo:['#ead9ad','#f3e8c7','#d3a84f','#c77b35','#a94932','#fff0c8'],pez:['#286fa8','#3b8fbd','#55aacb','#1f557f','#79c4d8','#91d6e3']};
function ruido(x,y,s){const n=Math.sin(x*127.1+y*311.7+s*17.3)*43758.5453;return n-Math.floor(n);}
function crearTextura(tipo){const S=128,c=document.createElement('canvas');c.width=c.height=S;const ctx=c.getContext('2d'),pal=PALETAS[tipo]||PALETAS.terreno,paso=8;ctx.fillStyle=pal[0];ctx.fillRect(0,0,S,S);for(let y=0;y<S;y+=paso)for(let x=0;x<S;x+=paso){const i=Math.floor(ruido(x,y,tipo.length)*pal.length);ctx.fillStyle=pal[i];ctx.beginPath();if(ruido(x+3,y+11,tipo.length+4)>.5){ctx.moveTo(x,y);ctx.lineTo(x+paso,y);ctx.lineTo(x,y+paso)}else{ctx.moveTo(x+paso,y);ctx.lineTo(x+paso,y+paso);ctx.lineTo(x,y+paso)}ctx.closePath();ctx.fill();if(ruido(x+19,y+7,tipo.length+8)>.78){ctx.fillStyle=pal[(i+2)%pal.length];ctx.globalAlpha=.42;ctx.beginPath();ctx.moveTo(x+2,y+2);ctx.lineTo(x+paso-2,y+3);ctx.lineTo(x+3,y+paso-2);ctx.closePath();ctx.fill();ctx.globalAlpha=1}}
const tex=new THREE.CanvasTexture(c);tex.magFilter=THREE.NearestFilter;tex.minFilter=THREE.NearestFilter;tex.generateMipmaps=false;return tex;}
function crearRelieve(tipo){const S=128,c=document.createElement('canvas');c.width=c.height=S;const ctx=c.getContext('2d');ctx.fillStyle='#777';ctx.fillRect(0,0,S,S);for(let y=0;y<S;y+=8)for(let x=0;x<S;x+=8){const v=Math.floor(65+ruido(x,y,tipo.length+99)*110);ctx.fillStyle=`rgb(${v},${v},${v})`;ctx.beginPath();if(ruido(x+5,y+2,7)>.5){ctx.moveTo(x,y);ctx.lineTo(x+8,y);ctx.lineTo(x,y+8)}else{ctx.moveTo(x+8,y);ctx.lineTo(x+8,y+8);ctx.lineTo(x,y+8)}ctx.closePath();ctx.fill()}const t=new THREE.CanvasTexture(c);t.magFilter=THREE.NearestFilter;t.minFilter=THREE.NearestFilter;t.generateMipmaps=false;return t;}
const texturas={},relieves={};Object.keys(PALETAS).forEach(k=>{texturas[k]=crearTextura(k);relieves[k]=crearRelieve(k)});
const estilizados=new WeakSet(),aguas=[];
function tipoLocal(n){const u=n.userData||{},id=u.pickup&&u.pickup.id,t=String(u.tipo||id||n.name||'').toLowerCase();if(t==='agua')return'agua';if(t==='cesped'||t==='terreno')return'terreno';if(t.includes('tierra'))return'tierra';if(t.includes('piedra'))return'piedra';if(t.includes('madera')||t==='tronco')return'madera';if(t==='palo')return'palo';if(t.includes('arena'))return'arena';if(t==='hojas')return'hojas';if(t==='mano'||t.includes('piel')||t.includes('humano'))return'humano';if(t==='vaca'||t==='oveja'||t==='pollo'||t==='pez')return t;return null;}
function detectarTipo(n){let a=n;while(a){const t=tipoLocal(a);if(t)return t;a=a.parent}return null;}
function colorOscuro(m){if(!m||!m.color)return false;return m.color.r<.12&&m.color.g<.12&&m.color.b<.12;}
function hacerPoligonal(material,tipo){if(!material)return;if(Array.isArray(material)){material.forEach(m=>hacerPoligonal(m,tipo));return}if(material.flatShading!==undefined)material.flatShading=true;if(tipo&&texturas[tipo]&&material.map!==undefined){if(!(tipo==='vaca'||tipo==='oveja'||tipo==='pollo'||tipo==='pez')||!colorOscuro(material)){material.map=texturas[tipo];if(material.color)material.color.set(0xffffff);if(material.bumpMap!==undefined){material.bumpMap=relieves[tipo];material.bumpScale=tipo==='humano'?.055:.09}}}if(material.shininess!==undefined&&tipo!=='agua')material.shininess=10;material.needsUpdate=true;}
function prepararAgua(n){if(n.userData.__aguaPoligonal)return;const g0=n.geometry;if(!g0||!g0.attributes||!g0.attributes.position)return;if(g0.clone)n.geometry=g0.clone();const g=n.geometry,pos=g.attributes.position;n.userData.__aguaPoligonal=true;n.userData.__aguaBase=new Float32Array(pos.array);n.userData.__aguaFase=ruido(n.position.x,n.position.z,31)*Math.PI*2;n.material=new THREE.MeshLambertMaterial({map:texturas.agua,transparent:true,opacity:.72,depthWrite:false,side:THREE.DoubleSide,flatShading:true});aguas.push(n);}
function animarAgua(t){for(let i=aguas.length-1;i>=0;i--){const n=aguas[i];if(!n||!n.parent){aguas.splice(i,1);continue}const pos=n.geometry.attributes.position,base=n.userData.__aguaBase,fase=n.userData.__aguaFase||0;for(let j=0;j<pos.count;j++){const k=j*3,x=base[k],z=base[k+2];pos.array[k+1]=base[k+1]+Math.sin(x*.72+t*1.7+fase)*.035+Math.cos(z*.58+t*1.25+fase)*.028}pos.needsUpdate=true}}
function aplicar(){const m=window.motor;if(!m||!m.escena)return;m.escena.traverse(n=>{if(!n||!n.isMesh)return;const tipo=detectarTipo(n);if(tipo&&!estilizados.has(n)){hacerPoligonal(n.material,tipo);estilizados.add(n)}else if(!tipo&&!estilizados.has(n)&&n.material&&n.material.flatShading!==undefined){n.material.flatShading=true;n.material.needsUpdate=true;estilizados.add(n)}if(tipo==='agua')prepararAgua(n)})}
const originalRender=THREE.WebGLRenderer.prototype.render;THREE.WebGLRenderer.prototype.render=function(scene,camera){if(window.motor&&window.motor.escena===scene)animarAgua(performance.now()*.001);return originalRender.call(this,scene,camera)};
setInterval(aplicar,500);window.WordSurvivalPoligonal={aplicar,animarAgua,texturas,relieves};
})();
