class GestorCriaturas {
constructor(motor,datos){this.m=motor;this.d=datos||{};this.lista=[];this.tiempoSpawn=0;this.maxTerrestres=24;this.maxPeces=12;this.texturas={};}
mat(c){return new THREE.MeshLambertMaterial({color:c});}
tex(n,c){try{const t=new THREE.TextureLoader().load(`textura/${n}.svg`);t.magFilter=THREE.NearestFilter;t.minFilter=THREE.NearestFilter;return new THREE.MeshLambertMaterial({map:t,color:c});}catch(e){return this.mat(c);}}
pieza(g,m,x,y,z,p){const q=new THREE.Mesh(g,m);q.position.set(x,y,z);p.add(q);return q;}
modeloAnimal(tipo){const p=new THREE.Group(),negro=this.mat(0x111111),blanco=this.mat(0xffffff),gris=this.mat(0x777777),amarillo=this.mat(0xf2c94c),rojo=this.mat(0xd62828),azul=this.mat(0x3b82f6);const px=()=>{const q=this.tex(tipo,0xffffff);return q;};
if(tipo==='vaca'){const m=px();const cuerpo=this.pieza(new THREE.BoxGeometry(1.8,.9,1.05),m,0,1.05,0,p);this.pieza(new THREE.BoxGeometry(.65,.65,.7),m,1.05,1.25,0,p);const patas=[[-.65,-.35],[.65,-.35],[-.65,.35],[.65,.35]].map(a=>this.pieza(new THREE.BoxGeometry(.22,.75,.22),blanco,a[0],.38,a[1],p));this.pieza(new THREE.BoxGeometry(.22,.18,.12),negro,1.38,1.38,-.22,p);this.pieza(new THREE.BoxGeometry(.22,.18,.12),negro,1.38,1.38,.22,p);const cuerno=new THREE.ConeGeometry(.13,.38,4);this.pieza(cuerno,gris,.98,1.75,-.22,p).rotation.z=-.45;this.pieza(cuerno,gris,.98,1.75,.22,p).rotation.z=-.45;p.userData.animacion={patas,modo:'caminar'};}
else if(tipo==='oveja'){const lana=this.mat(0xf5f5f5);const patas=[[-.6,-.3],[.6,-.3],[-.6,.3],[.6,.3]].map(a=>this.pieza(new THREE.BoxGeometry(.2,.7,.2),gris,a[0],.35,a[1],p));this.pieza(new THREE.BoxGeometry(1.7,1,1),lana,0,1,0,p);[[-.55,0],[0,0],[.55,0],[-.3,.35],[.3,.35],[-.3,-.35],[.3,-.35]].forEach(a=>this.pieza(new THREE.BoxGeometry(.55,.55,.55),lana,a[0],1.2,a[1],p));this.pieza(new THREE.BoxGeometry(.55,.65,.6),gris,1,1.2,0,p);this.pieza(new THREE.BoxGeometry(.12,.12,.08),negro,1.28,1.3,-.18,p);this.pieza(new THREE.BoxGeometry(.12,.12,.08),negro,1.28,1.3,.18,p);p.userData.animacion={patas,modo:'caminar'};}
else if(tipo==='pollo'){const cuerpo=this.pieza(new THREE.BoxGeometry(.8,.75,.7),this.tex('pollo',0xfff8e8),0,.8,0,p);const patas=[this.pieza(new THREE.BoxGeometry(.12,.45,.12),amarillo,-.2,.3,0,p),this.pieza(new THREE.BoxGeometry(.12,.45,.12),amarillo,.2,.3,0,p)];this.pieza(new THREE.BoxGeometry(.5,.5,.5),blanco,.48,1.05,0,p);this.pieza(new THREE.ConeGeometry(.12,.28,4),amarillo,.78,1.05,0,p).rotation.z=Math.PI/2;this.pieza(new THREE.BoxGeometry(.16,.18,.12),rojo,.38,1.38,0,p);this.pieza(new THREE.BoxGeometry(.08,.08,.08),negro,.66,1.18,-.18,p);this.pieza(new THREE.BoxGeometry(.08,.08,.08),negro,.66,1.18,.18,p);p.userData.animacion={patas,modo:'caminar'};}
else if(tipo==='pez'){const m=this.tex('pez',0x3b82f6);this.pieza(new THREE.SphereGeometry(.38,10,8),m,0,0,0,p);const cola=this.pieza(new THREE.ConeGeometry(.22,.5,4),m,-.48,0,0,p);cola.rotation.z=-Math.PI/2;const aleta=this.pieza(new THREE.ConeGeometry(.13,.28,4),m,.05,.28,0,p);const ojos=[this.pieza(new THREE.SphereGeometry(.045,6,6),blanco,.22,.12,-.13,p),this.pieza(new THREE.SphereGeometry(.045,6,6),blanco,.22,.12,.13,p)];p.userData.animacion={cola,aleta,modo:'nadar'};}
return p;}
crear(tipo,x,z,opciones={}){const d=this.d[tipo];if(!d||!this.m||!this.m.mundo)return null;const pez=tipo==='pez',agua=this.m.mundo.esAgua(x,z);if(pez&&!agua)return null;if(!pez&&agua)return null;const y=pez?this.m.mundo.getWaterHeightAt(x,z)-.45:this.m.getGroundHeightAt(x,z);const modelo=this.modeloAnimal(tipo);modelo.position.set(x,y,z);this.m.escena.add(modelo);const c={tipo,x,y,z,vida:d.vida,vidaMax:d.vida,daño:0,modelo,direccion:Math.random()*Math.PI*2,velocidad:d.velocidad||1,caminando:true,tiempoMovimiento:1+Math.random()*3,acuatico:pez,edad:0,faseAnimacion:Math.random()*Math.PI*2};this.lista.push(c);return c;}
posicionAleatoria(){if(!this.m||!this.m.j||!this.m.mundo)return null;for(let i=0;i<100;i++){const a=Math.random()*Math.PI*2,d=12+Math.random()*55,x=this.m.j.x+Math.cos(a)*d,z=this.m.j.z+Math.sin(a)*d;if(!this.m.mundo.esAgua(x,z))return[x,z];}return null;}
buscarAgua(){if(!this.m||!this.m.j||!this.m.mundo)return null;for(let i=0;i<100;i++){const a=Math.random()*Math.PI*2,d=12+Math.random()*55,x=this.m.j.x+Math.cos(a)*d,z=this.m.j.z+Math.sin(a)*d;if(this.m.mundo.esAgua(x,z))return[x,z];}return null;}
generarIniciales(){const iniciales=[['vaca',8,8],['vaca',-12,5],['vaca',15,-10],['oveja',-18,-8],['oveja',20,12],['oveja',-20,15],['pollo',12,-18],['pollo',-8,-14],['pollo',18,4]];iniciales.forEach(p=>this.crear(p[0],p[1],p[2]));let peces=0;for(let i=0;i<80&&peces<8;i++){const p=this.buscarAgua();if(p&&this.crear('pez',p[0],p[1]))peces++;}}
contar(acuatico){return this.lista.filter(c=>c.acuatico===acuatico&&c.vida>0).length;}
spawnContinuo(){if(!this.m||!this.m.j)return;const terrestres=this.contar(false),peces=this.contar(true);if(terrestres<this.maxTerrestres){const p=this.posicionAleatoria();if(p){const tipos=['vaca','oveja','pollo'];this.crear(tipos[Math.floor(Math.random()*tipos.length)],p[0],p[1]);}}if(peces<this.maxPeces){const p=this.buscarAgua();if(p)this.crear('pez',p[0],p[1]);}}
recibirDaño(cantidad){if(!this.m||!this.m.j)return;let objetivo=null,distancia=Infinity;for(const c of this.lista){const d=Math.hypot(this.m.j.x-c.x,this.m.j.z-c.z);if(c.vida>0&&d<2.5&&d<distancia){objetivo=c;distancia=d;}}if(!objetivo)return;objetivo.vida-=cantidad;if(objetivo.vida<=0&&objetivo.modelo.parent)objetivo.modelo.parent.remove(objetivo.modelo);this.lista=this.lista.filter(c=>c.vida>0);}
cambiarDireccion(c){c.direccion=Math.random()*Math.PI*2;}
actualizar(dt=.016){this.tiempoSpawn+=dt;if(this.tiempoSpawn>=3){this.tiempoSpawn=0;this.spawnContinuo();}for(const c of this.lista){c.edad+=dt;c.faseAnimacion+=dt*6;c.tiempoMovimiento-=dt;if(c.tiempoMovimiento<=0){c.caminando=Math.random()>.25;c.tiempoMovimiento=1.5+Math.random()*4;if(c.caminando)this.cambiarDireccion(c);}const anim=c.modelo.userData.animacion;if(anim&&c.caminando){const paso=Math.sin(c.faseAnimacion)*.38;if(anim.patas)anim.patas.forEach((p,i)=>p.rotation.x=paso*(i%2===0?1:-1));}if(anim&&anim.modo==='nadar'){anim.cola.rotation.y=Math.sin(c.faseAnimacion)*.35;anim.aleta.rotation.x=Math.sin(c.faseAnimacion)*.2;}if(!c.caminando)continue;const nx=c.x+Math.sin(c.direccion)*c.velocidad*dt,nz=c.z+Math.cos(c.direccion)*c.velocidad*dt;if(!this.m.mundo)continue;const agua=this.m.mundo.esAgua(nx,nz);if(c.acuatico){if(!agua){this.cambiarDireccion(c);continue;}c.x=nx;c.z=nz;c.y=this.m.mundo.getWaterHeightAt(c.x,c.z)-.45+Math.sin(c.edad*3+c.x)*.08;}else{if(agua){this.cambiarDireccion(c);continue;}c.x=nx;c.z=nz;c.y=this.m.getGroundHeightAt(c.x,c.z);}c.modelo.position.set(c.x,c.y,c.z);c.modelo.rotation.y=c.direccion;}}
}
window.GestorCriaturas=GestorCriaturas;
