class Jugador {
 constructor(){this.x=0;this.y=.6;this.z=0;this.hp=100;this.maxHp=100;this.mana=100;this.hambre=100;this.nivel=1;this.exp=0;this.expSig=120;this.vivo=true;this.corriendo=false;this.saltando=false;this.modelo=new THREE.Group();const tex=new THREE.TextureLoader().load('textura/humano.svg');tex.magFilter=THREE.LinearFilter;tex.minFilter=THREE.LinearFilter;const mat=new THREE.MeshLambertMaterial({map:tex});const skin=new THREE.MeshLambertMaterial({color:0xc9875f});const shirt=new THREE.MeshLambertMaterial({color:0x293241});const pants=new THREE.MeshLambertMaterial({color:0x374151});const body=new THREE.Mesh(new THREE.CylinderGeometry(.29,.34,1.05,10),shirt);body.position.y=.58;body.name='torso';this.modelo.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.32,12,10),skin);head.scale.y=1.08;head.position.y=1.34;head.name='head';this.modelo.add(head);const hair=new THREE.Mesh(new THREE.SphereGeometry(.335,12,8,0,Math.PI*2,0,Math.PI*.42),new THREE.MeshLambertMaterial({color:0x2b1b12}));hair.position.y=1.55;this.modelo.add(hair);const legGeo=new THREE.BoxGeometry(.18,.75,.22);for(const s of [-1,1]){const leg=new THREE.Mesh(legGeo,pants);leg.position.set(.15*s,.0,0);this.modelo.add(leg);}const armGeo=new THREE.CylinderGeometry(.09,.11,.72,8);this.leftArm=new THREE.Mesh(armGeo,shirt);this.rightArm=new THREE.Mesh(armGeo,shirt);this.leftArm.name='leftArm';this.rightArm.name='rightArm';this.leftArm.position.set(-.38,.82,0);this.rightArm.position.set(.38,.82,0);this.leftArm.rotation.z=.12;this.rightArm.rotation.z=-.12;this.modelo.add(this.leftArm,this.rightArm);this.leftHand=this.crearMano();this.rightHand=this.crearMano();this.leftHand.position.set(-.42,.45,0);this.rightHand.position.set(.42,.45,0);this.leftHand.name='leftHand';this.rightHand.name='rightHand';this.modelo.add(this.leftHand,this.rightHand);this.leftHandHeld=false;this.rightHandHeld=false;}
 crearMano(){const g=new THREE.Group(),mat=new THREE.MeshLambertMaterial({color:0xd08b62}),p=new THREE.Mesh(new THREE.SphereGeometry(.13,8,6),mat);g.add(p);for(let i=0;i<4;i++){const f=new THREE.Mesh(new THREE.CylinderGeometry(.025,.032,.16,6),mat);f.rotation.z=Math.PI/2;f.position.set((i-1.5)*.045,.015,-.11);g.add(f);}return g;}
 agregarAEscena(e){e.add(this.modelo);} actualizarPosicion(){this.modelo.position.set(this.x,this.y-.6,this.z);} recibirDaño(c){if(!this.vivo)return;this.hp=Math.max(0,this.hp-c);if(this.hp<=0)this.vivo=false;} curar(c){this.hp=Math.min(this.maxHp,this.hp+c);} ganarExperiencia(c){this.exp+=c;if(this.exp>=this.expSig){this.nivel++;this.exp=0;this.expSig*=1.2;}}
 setFirstPerson(fp){this.leftArm.visible=!!fp;this.rightArm.visible=!!fp;this.leftHand.visible=!!fp;this.rightHand.visible=!!fp;this.modelo.children.forEach(c=>{if(['leftArm','rightArm','leftHand','rightHand'].includes(c.name))return;c.visible=!fp;});}
 actualizarManos(cam,izquierda,derecha){this.leftHandHeld=!!izquierda;this.rightHandHeld=!!derecha;this.seguirMouse(cam,izquierda,derecha);}
 seguirMouse(cam,activaIzquierda,activaDerecha){if(!cam)return;const tx=THREE.MathUtils.clamp(cam.rotation.x*1.05,-1.15,1.15),ty=THREE.MathUtils.clamp(cam.rotation.y*1.05,-1.15,1.15);for(const [mano,brazo,activa,lado] of [[this.leftHand,this.leftArm,activaIzquierda,-1],[this.rightHand,this.rightArm,activaDerecha,1]]){if(activa){brazo.rotation.x+=(tx-brazo.rotation.x)*.2;brazo.rotation.y+=(ty-brazo.rotation.y)*.2;brazo.rotation.z+=((-.12*lado)-brazo.rotation.z)*.2;mano.rotation.x+=(tx*1.15-mano.rotation.x)*.28;mano.rotation.y+=(ty*1.15-mano.rotation.y)*.28;mano.rotation.z+=((ty*.5+lado*.08)-mano.rotation.z)*.25;mano.position.x+=((lado*.42+ty*.08)-mano.position.x)*.2;mano.position.y+=((.45-tx*.12)-mano.position.y)*.2;}else{brazo.rotation.x*=.82;brazo.rotation.y*=.82;brazo.rotation.z+=((-.12*lado)-brazo.rotation.z)*.18;mano.rotation.x*=.8;mano.rotation.y*=.8;mano.rotation.z*=.8;mano.position.x+=((lado*.42)-mano.position.x)*.18;mano.position.y+=((.45)-mano.position.y)*.18;}}}
 actualizarHUD(){const ids=[['lvl',this.nivel],['pos',`X:${Math.round(this.x)} Z:${Math.round(this.z)}`]];ids.forEach(a=>{const e=document.getElementById(a[0]);if(e)e.textContent=a[1];});[['b-hp',this.hp],['b-mana',this.mana],['b-exp',this.exp/this.expSig*100],['b-hambre',this.hambre]].forEach(a=>{const e=document.getElementById(a[0]);if(e)e.style.width=a[1]+'%';});}
}
window.Jugador=Jugador;