class Jugador {
 constructor(){this.x=0;this.y=.6;this.z=0;this.hp=100;this.maxHp=100;this.mana=100;this.hambre=100;this.nivel=1;this.exp=0;this.expSig=120;this.vivo=true;this.corriendo=false;this.saltando=false;this.modelo=new THREE.Group();const tex=new THREE.TextureLoader().load('textura/humano.svg');tex.magFilter=THREE.LinearFilter;tex.minFilter=THREE.LinearFilter;const mat=new THREE.MeshLambertMaterial({map:tex});const skin=new THREE.MeshLambertMaterial({color:0xc9875f});const shirt=new THREE.MeshLambertMaterial({color:0x293241});const pants=new THREE.MeshLambertMaterial({color:0x374151});const body=new THREE.Mesh(new THREE.CylinderGeometry(.29,.34,1.05,10),shirt);body.position.y=.58;body.name='torso';this.modelo.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.32,12,10),skin);head.scale.y=1.08;head.position.y=1.34;head.name='head';this.modelo.add(head);const hair=new THREE.Mesh(new THREE.SphereGeometry(.335,12,8,0,Math.PI*2,0,Math.PI*.42),new THREE.MeshLambertMaterial({color:0x2b1b12}));hair.position.y=1.55;this.modelo.add(hair);const legGeo=new THREE.BoxGeometry(.18,.75,.22);for(const s of [-1,1]){const leg=new THREE.Mesh(legGeo,pants);leg.position.set(.15*s,.0,0);this.modelo.add(leg);}this.leftShoulder=new THREE.Group();this.rightShoulder=new THREE.Group();this.leftShoulder.name='leftShoulder';this.rightShoulder.name='rightShoulder';this.leftShoulder.position.set(-.38,1.0,0);this.rightShoulder.position.set(.38,1.0,0);this.modelo.add(this.leftShoulder,this.rightShoulder);const armGeo=new THREE.CylinderGeometry(.09,.11,.72,8);this.leftArm=new THREE.Mesh(armGeo,shirt);this.rightArm=new THREE.Mesh(armGeo,shirt);this.leftArm.name='leftArm';this.rightArm.name='rightArm';this.leftArm.position.y=-.36;this.rightArm.position.y=-.36;this.leftShoulder.add(this.leftArm);this.rightShoulder.add(this.rightArm);this.leftHand=this.crearMano();this.rightHand=this.crearMano();this.leftHand.position.y=-.76;this.rightHand.position.y=-.76;this.leftHand.name='leftHand';this.rightHand.name='rightHand';this.leftArm.add(this.leftHand);this.rightArm.add(this.rightHand);this.leftHandHeld=false;this.rightHandHeld=false;}
 crearMano(){const g=new THREE.Group(),mat=new THREE.MeshLambertMaterial({color:0xd08b62}),p=new THREE.Mesh(new THREE.SphereGeometry(.13,8,6),mat);g.add(p);for(let i=0;i<4;i++){const f=new THREE.Mesh(new THREE.CylinderGeometry(.025,.032,.16,6),mat);f.rotation.z=Math.PI/2;f.position.set((i-1.5)*.045,.015,-.11);g.add(f);}return g;}
 agregarAEscena(e){e.add(this.modelo);} actualizarPosicion(){this.modelo.position.set(this.x,this.y-.6,this.z);} recibirDaño(c){if(!this.vivo)return;this.hp=Math.max(0,this.hp-c);if(this.hp<=0)this.vivo=false;} curar(c){this.hp=Math.min(this.maxHp,this.hp+c);} ganarExperiencia(c){this.exp+=c;if(this.exp>=this.expSig){this.nivel++;this.exp=0;this.expSig*=1.2;}}
 setFirstPerson(fp){this.leftShoulder.visible=!!fp;this.rightShoulder.visible=!!fp;this.modelo.children.forEach(c=>{if(['leftShoulder','rightShoulder'].includes(c.name))return;c.visible=!fp;});}
 actualizarManos(cam,izquierda,derecha){this.leftHandHeld=!!izquierda;this.rightHandHeld=!!derecha;this.seguirMouse(cam,izquierda,derecha);}
 seguirMouse(cam,activaIzquierda,activaDerecha){if(!cam)return;const pitch=THREE.MathUtils.clamp(cam.rotation.x,-1.15,1.15),yaw=THREE.MathUtils.clamp(cam.rotation.y,-1.15,1.15);for(const [hombro,brazo,mano,activa,lado] of [[this.leftShoulder,this.leftArm,this.leftHand,activaIzquierda,-1],[this.rightShoulder,this.rightArm,this.rightHand,activaDerecha,1]]){if(activa){const objetivoX=pitch*.92;const objetivoY=yaw*.92;hombro.rotation.x+=(objetivoX-hombro.rotation.x)*.18;hombro.rotation.y+=(objetivoY-hombro.rotation.y)*.18;hombro.rotation.z+=((lado*.08)-hombro.rotation.z)*.18;brazo.rotation.x+=((pitch*.25)-brazo.rotation.x)*.18;brazo.rotation.y+=((yaw*.18)-brazo.rotation.y)*.18;brazo.rotation.z+=((-lado*.08)-brazo.rotation.z)*.18;mano.rotation.x+=((pitch*.35)-mano.rotation.x)*.25;mano.rotation.y+=((yaw*.3)-mano.rotation.y)*.25;}else{hombro.rotation.x*=.84;hombro.rotation.y*=.84;hombro.rotation.z+=((lado*.08)-hombro.rotation.z)*.18;brazo.rotation.x*=.84;brazo.rotation.y*=.84;brazo.rotation.z+=((-lado*.08)-brazo.rotation.z)*.18;mano.rotation.x*=.8;mano.rotation.y*=.8;}}}
 actualizarHUD(){const ids=[['lvl',this.nivel],['pos',`X:${Math.round(this.x)} Z:${Math.round(this.z)}`]];ids.forEach(a=>{const e=document.getElementById(a[0]);if(e)e.textContent=a[1];});[['b-hp',this.hp],['b-mana',this.mana],['b-exp',this.exp/this.expSig*100],['b-hambre',this.hambre]].forEach(a=>{const e=document.getElementById(a[0]);if(e)e.style.width=a[1]+'%';});}
}
window.Jugador=Jugador;