class Jugador {
 constructor(){this.x=0;this.y=.6;this.z=0;this.hp=100;this.maxHp=100;this.mana=100;this.hambre=100;this.nivel=1;this.exp=0;this.expSig=120;this.vivo=true;this.corriendo=false;this.saltando=false;this.tiempoAnim=0;this.modelo=new THREE.Group();
 const skin=new THREE.MeshLambertMaterial({color:0xc9875f}),shirt=new THREE.MeshLambertMaterial({color:0x293241}),pants=new THREE.MeshLambertMaterial({color:0x374151}),shoe=new THREE.MeshLambertMaterial({color:0x171717}),hairMat=new THREE.MeshLambertMaterial({color:0x2b1b12});
 this.modelo.name='playerModel';
 const pelvis=new THREE.Mesh(new THREE.BoxGeometry(.52,.28,.34),pants);pelvis.position.y=.38;pelvis.name='pelvis';this.modelo.add(pelvis);
 const body=new THREE.Mesh(new THREE.CylinderGeometry(.29,.34,1.05,10),shirt);body.position.y=.88;body.name='torso';this.modelo.add(body);
 const neck=new THREE.Mesh(new THREE.CylinderGeometry(.11,.13,.18,8),skin);neck.position.y=1.48;neck.name='neck';this.modelo.add(neck);
 const head=new THREE.Mesh(new THREE.SphereGeometry(.32,12,10),skin);head.scale.y=1.08;head.position.y=1.78;head.name='head';this.modelo.add(head);
 const hair=new THREE.Mesh(new THREE.SphereGeometry(.335,12,8,0,Math.PI*2,0,Math.PI*.48),hairMat);hair.position.y=1.99;hair.name='hair';this.modelo.add(hair);
 for(const s of [-1,1]){const ear=new THREE.Mesh(new THREE.SphereGeometry(.07,7,6),skin);ear.position.set(.32*s,1.79,0);this.modelo.add(ear);}
 this.leftLeg=this.crearPierna(-1,pants,shoe);this.rightLeg=this.crearPierna(1,pants,shoe);this.modelo.add(this.leftLeg,this.rightLeg);
 this.leftShoulder=new THREE.Group();this.rightShoulder=new THREE.Group();this.leftShoulder.name='leftShoulder';this.rightShoulder.name='rightShoulder';this.leftShoulder.position.set(-.38,1.28,0);this.rightShoulder.position.set(.38,1.28,0);this.modelo.add(this.leftShoulder,this.rightShoulder);
 const armGeo=new THREE.CylinderGeometry(.09,.11,.72,8);this.leftArm=new THREE.Mesh(armGeo,shirt);this.rightArm=new THREE.Mesh(armGeo,shirt);this.leftArm.name='leftArm';this.rightArm.name='rightArm';this.leftArm.position.y=-.36;this.rightArm.position.y=-.36;this.leftShoulder.add(this.leftArm);this.rightShoulder.add(this.rightArm);
 this.leftHand=this.crearMano();this.rightHand=this.crearMano();this.leftHand.position.y=-.76;this.rightHand.position.y=-.76;this.leftHand.name='leftHand';this.rightHand.name='rightHand';this.leftArm.add(this.leftHand);this.rightArm.add(this.rightHand);this.leftHandHeld=false;this.rightHandHeld=false;}
 crearPierna(lado,pants,shoe){const g=new THREE.Group();g.name=lado<0?'leftLeg':'rightLeg';const leg=new THREE.Mesh(new THREE.CylinderGeometry(.105,.13,.72,8),pants);leg.position.y=-.36;g.add(leg);const foot=new THREE.Mesh(new THREE.BoxGeometry(.22,.14,.38),shoe);foot.position.set(0,-.78,.09);foot.name=lado<0?'leftFoot':'rightFoot';g.add(foot);g.position.set(.15*lado,.38,0);return g;}
 crearMano(){const g=new THREE.Group(),mat=new THREE.MeshLambertMaterial({color:0xd08b62}),p=new THREE.Mesh(new THREE.SphereGeometry(.13,8,6),mat);g.add(p);for(let i=0;i<4;i++){const f=new THREE.Mesh(new THREE.CylinderGeometry(.025,.032,.16,6),mat);f.rotation.z=Math.PI/2;f.position.set((i-1.5)*.045,.015,-.11);g.add(f);}return g;}
 agregarAEscena(e){e.add(this.modelo);}
 actualizarPosicion(){this.modelo.position.set(this.x,this.y-.6,this.z);this.animarMovimiento();}
 animarMovimiento(){const velocidad=this.corriendo?.22:.14;const moviendo=this.velocidadMovimiento>0.01||this.corriendo;if(!moviendo){this.leftLeg.rotation.x*=.78;this.rightLeg.rotation.x*=.78;this.leftShoulder.rotation.x*=.78;this.rightShoulder.rotation.x*=.78;return;}this.tiempoAnim+=velocidad;const a=Math.sin(this.tiempoAnim)*(.65+(this.corriendo?.18:0));this.leftLeg.rotation.x=a;this.rightLeg.rotation.x=-a;this.leftShoulder.rotation.x=-a*.65;this.rightShoulder.rotation.x=a*.65;this.modelo.position.y=(this.y-.6)+(Math.abs(Math.sin(this.tiempoAnim*2))*.035);}
 recibirDaño(c){if(!this.vivo)return;this.hp=Math.max(0,this.hp-c);if(this.hp<=0)this.vivo=false;} curar(c){this.hp=Math.min(this.maxHp,this.hp+c);} ganarExperiencia(c){this.exp+=c;if(this.exp>=this.expSig){this.nivel++;this.exp=0;this.expSig*=1.2;}}
 setFirstPerson(fp){this.leftShoulder.visible=!!fp;this.rightShoulder.visible=!!fp;this.modelo.children.forEach(c=>{if(['leftShoulder','rightShoulder'].includes(c.name))return;c.visible=!fp;});}
 actualizarManos(cam,izquierda,derecha){this.leftHandHeld=!!izquierda;this.rightHandHeld=!!derecha;this.seguirMouse(cam,izquierda,derecha);}
 seguirMouse(cam,activaIzquierda,activaDerecha){if(!cam)return;const pitch=THREE.MathUtils.clamp(cam.rotation.x,-1.15,1.15),yaw=THREE.MathUtils.clamp(cam.rotation.y,-1.15,1.15);for(const [hombro,brazo,mano,activa,lado] of [[this.leftShoulder,this.leftArm,this.leftHand,activaIzquierda,-1],[this.rightShoulder,this.rightArm,this.rightHand,activaDerecha,1]]){if(activa){const objetivoX=pitch*.92,objetivoY=yaw*.92;hombro.rotation.x+=(objetivoX-hombro.rotation.x)*.18;hombro.rotation.y+=(objetivoY-hombro.rotation.y)*.18;hombro.rotation.z+=((lado*.08)-hombro.rotation.z)*.18;brazo.rotation.x+=((pitch*.25)-brazo.rotation.x)*.18;brazo.rotation.y+=((yaw*.18)-brazo.rotation.y)*.18;brazo.rotation.z+=((-lado*.08)-brazo.rotation.z)*.18;mano.rotation.x+=((pitch*.35)-mano.rotation.x)*.25;mano.rotation.y+=((yaw*.3)-mano.rotation.y)*.25;}else{hombro.rotation.x*=.84;hombro.rotation.y*=.84;hombro.rotation.z+=((lado*.08)-hombro.rotation.z)*.18;brazo.rotation.x*=.84;brazo.rotation.y*=.84;brazo.rotation.z+=((-lado*.08)-brazo.rotation.z)*.18;mano.rotation.x*=.8;mano.rotation.y*=.8;}}}
 actualizarHUD(){const ids=[['lvl',this.nivel],['pos',`X:${Math.round(this.x)} Z:${Math.round(this.z)}`]];ids.forEach(a=>{const e=document.getElementById(a[0]);if(e)e.textContent=a[1];});[['b-hp',this.hp],['b-mana',this.mana],['b-exp',this.exp/this.expSig*100],['b-hambre',this.hambre]].forEach(a=>{const e=document.getElementById(a[0]);if(e)e.style.width=a[1]+'%';});}
}
window.Jugador=Jugador;