const motor=new Motor();window.motor=motor;
// Agua: permite entrar y bajar dentro del agua.
try{const movimientoOriginal=motor._updateMovement;const codigo=movimientoOriginal.toString();const codigoAgua=codigo.replace("this.j.y=Math.max(this.getGroundHeightAt(this.j.x,this.j.z)+.18,Math.min(water+.25,this.j.y));","this.j.y=Math.max(this.getGroundHeightAt(this.j.x,this.j.z)+.18,this.j.y);");if(codigoAgua!==codigo)motor._updateMovement=eval('('+codigoAgua+')');}catch(e){console.warn('No se pudo habilitar inmersion:',e);}
// Recoleccion en dos manos: E solo recoge exactamente el objeto apuntado.
// No existe inventario: solo hay mano derecha y mano izquierda.
motor.manoDerechaObjeto=null;
motor.manoIzquierdaObjeto=null;
motor.manoSiguiente='derecha';
const colocarEnMano=function(o,mano){const mano3d=mano==='izquierda'?this.j.leftHand:this.j.rightHand;if(!mano3d||!o)return false;this.retirarObjeto(o);o.userData.mano=mano;mano3d.add(o);o.position.set(0,-.22,-.16);o.rotation.set(0,0,mano==='izquierda'?-0.12:0.12);o.scale.setScalar(1.15);if(mano==='izquierda')this.manoIzquierdaObjeto=o;else this.manoDerechaObjeto=o;this.equipado=(o.userData.pickup.id==='pala_madera'||o.userData.pickup.id==='pico_piedra')?o:(this.equipado&&this.equipado.parent?this.equipado:null);return true;};
const recogerSoloApuntado=function(){const hit=this.encontrarHit();let o=hit&&hit.object;while(o&&!o.userData.pickup)o=o.parent;if(!o){this.mostrarMensaje('Apunta directamente al objeto que quieres recoger.');return;}if(this.manoDerechaObjeto&&this.manoIzquierdaObjeto){this.mostrarMensaje('Tienes las dos manos ocupadas.');return;}const mano=!this.manoDerechaObjeto?'derecha':'izquierda';if(colocarEnMano.call(this,o,mano)){this.mostrarMensaje(`Mano ${mano}: ${o.userData.pickup.name}`);}};
motor.equiparCercano=recogerSoloApuntado;
motor.agarrar=function(){this.equiparCercano();};
// Soltar el objeto que esté en la mano izquierda o derecha sin usar inventario.
motor.desequipar=function(mano=null){const manos=mano?[mano]:(this.manoDerechaObjeto?['derecha']:['izquierda']);for(const lado of manos){const o=lado==='izquierda'?this.manoIzquierdaObjeto:this.manoDerechaObjeto;if(!o)continue;const p=this.j[lado==='izquierda'?'leftHand':'rightHand'].getWorldPosition(new THREE.Vector3());const id=o.userData.pickup.id,nombre=o.userData.pickup.name;this.j[lado==='izquierda'?'leftHand':'rightHand'].remove(o);if(lado==='izquierda')this.manoIzquierdaObjeto=null;else this.manoDerechaObjeto=null;if(this.equipado===o)this.equipado=null;this.crearObjeto(id,nombre,p.x,p.z,1,p.y-.08);return;}};
// El objeto que se use como herramienta puede estar en cualquiera de las dos manos.
motor.tieneHerramienta=function(id){return (this.manoDerechaObjeto&&this.manoDerechaObjeto.userData.pickup.id===id)||(this.manoIzquierdaObjeto&&this.manoIzquierdaObjeto.userData.pickup.id===id);};
// Modelos físicos correspondientes para los objetos equipables.
try{const crearOriginal=motor.crearObjeto.bind(motor);motor.crearObjeto=function(id,nombre,x,z,qty=1,yOverride=null){const m=crearOriginal(id,nombre,x,z,qty,yOverride);if(!m)return m;let g=null;if(id==='pala_madera'){g=new THREE.Group();const mango=new THREE.Mesh(new THREE.CylinderGeometry(.035,.045,.62,8),new THREE.MeshLambertMaterial({color:0x9b5a2e}));const hoja=new THREE.Mesh(new THREE.BoxGeometry(.16,.22,.045),new THREE.MeshLambertMaterial({color:0x777777}));mango.position.y=-.18;hoja.position.y=.18;hoja.rotation.x=-.12;g.add(mango,hoja);}else if(id==='pico_piedra'){g=new THREE.Group();const mango=new THREE.Mesh(new THREE.CylinderGeometry(.035,.045,.62,8),new THREE.MeshLambertMaterial({color:0x9b5a2e}));const cabeza=new THREE.Mesh(new THREE.BoxGeometry(.34,.07,.08),new THREE.MeshLambertMaterial({color:0x8d99a6}));cabeza.position.y=.18;g.add(mango,cabeza);}if(g){m.geometry.dispose();m.geometry=new THREE.BufferGeometry();m.add(g);m.userData.modeloHerramienta=g;}return m;};}catch(e){console.warn('No se pudieron preparar modelos de herramientas:',e);}
// Cada bloque de terreno es independiente. Con 4 bloques por unidad, cada cubo mide 0.25 x 0.25.
// La pala usa el bloque exacto bajo el puntero y solo ese bloque se destruye.
const btnEmpezar=document.getElementById('btn-empezar');const btnOpciones=document.getElementById('btn-opciones');const btnIdiomas=document.getElementById('btn-idiomas');const panelOpciones=document.getElementById('panel-opciones');const panelIdiomas=document.getElementById('panel-idiomas');
if(btnOpciones)btnOpciones.onclick=()=>{if(panelOpciones)panelOpciones.style.display=panelOpciones.style.display==='block'?'none':'block';if(panelIdiomas)panelIdiomas.style.display='none';};
if(btnIdiomas)btnIdiomas.onclick=()=>{if(panelIdiomas)panelIdiomas.style.display=panelIdiomas.style.display==='block'?'none':'block';if(panelOpciones)panelOpciones.style.display='none';};
if(btnEmpezar)btnEmpezar.onclick=()=>{const pantallaInicio=document.getElementById('pantalla-inicio'),hudJuego=document.getElementById('hud-juego');if(pantallaInicio)pantallaInicio.style.display='none';if(hudJuego)hudJuego.style.display='block';window.WORLD_SEED=Math.floor(Math.random()*2147483647);motor.iniciar();if(typeof Crafteos!=='undefined')motor.crafteos=new Crafteos(motor);if(typeof GestorLenguaje!=='undefined'){motor.lenguaje=new GestorLenguaje(motor);motor.lenguaje.cargarDatos();}window.GAME_CONFIG=window.GAME_CONFIG||{};window.GAME_CONFIG.fpEnabled=true;window.GAME_CONFIG.fpHeight=0.90;const btnCamera=document.getElementById('btn-toggle-camera');if(btnCamera){btnCamera.textContent='Cámara: 1ª';btnCamera.onclick=()=>{motor.toggleCamera();btnCamera.textContent=motor.cameraMode==='first'?'Cámara: 1ª':'Cámara: 3ª';};}const chk=document.getElementById('chk-crosshair'),cross=document.getElementById('crosshair');if(chk&&cross){cross.style.display=chk.checked?'block':'none';chk.onchange=()=>cross.style.display=chk.checked?'block':'none';}const fp=document.getElementById('chk-fp');if(fp){fp.checked=true;fp.disabled=false;fp.title='Primera persona muestra las manos; tercera persona muestra el modelo completo.';}};
