class Mundo {
constructor(m,seed){this.m=m;this.chunks=new Map();this.tam=16;this.radioCarga=5;this.radioEliminar=6;this.seed=seed||Math.random()*100000;this.nivelAgua=0;this.tiempoAgua=0;this._materiales={tronco:new THREE.MeshLambertMaterial({color:0x6b3f20}),hojas:new THREE.MeshLambertMaterial({color:0x176b32}),roca:new THREE.MeshLambertMaterial({color:0x73777d})};}
ruidoSuave(x,z){const n=Math.sin((x*127.1+z*311.7+this.seed)*12.9898)*43758.5453;return n-Math.floor(n);}
altura(x,z){const s=this.seed;const base=ruido(x*.018+s,z*.018+s)*10;const detalle=ruido(x*.055+s*.3,z*.055+s*.3)*3;const mont=Math.pow(Math.max(0,ruido(x*.009+s*.7,z*.009+s*.7)-.42),1.7)*30;return base*.35+detalle*.2+mont-3;}
tipoBloque(h){if(h<0)return'agua';if(h<.8)return'arena';if(h<8)return'cesped';if(h<13)return'tierra';return'piedra';}
esAgua(x,z){return this.altura(x,z)<this.nivelAgua;}
getWaterHeightAt(x,z){return this.esAgua(x,z)?this.nivelAgua:null;}
puedeCaminarEn(){return true;}
crearArbol(x,z,h,chunk){const arbol=new THREE.Group();const vari=this.ruidoSuave(x+11,z+7);const tronco=new THREE.Mesh(new THREE.CylinderGeometry(.28+.12*vari,.48+.14*vari,4.3+vari,10),this._materiales.tronco.clone());tronco.position.y=2.15;arbol.add(tronco);for(let i=0;i<5;i++){const copa=new THREE.Mesh(new THREE.SphereGeometry(1.35+vari*.7-i*.08,12,9),this._materiales.hojas.clone());copa.position.set((i%2-.5)*.65,4.35+i*.38,(i*.31-.45));copa.scale.set(1.05,.8,1.05);arbol.add(copa);}arbol.position.set(x,h,z);arbol.userData.recurso={madera:3,palo:1};tronco.userData.recurso=arbol.userData.recurso;chunk.objetos.push(arbol);chunk.grupo.add(arbol);}
crearRoca(x,z,h,chunk){const r=this.ruidoSuave(x,z);if(r>.045)return;const roca=new THREE.Mesh(new THREE.DodecahedronGeometry(.65+.5*r,2),this._materiales.roca.clone());roca.position.set(x,h+.35+.3*r,z);roca.scale.set(1+.35*r,.65+.5*r,.8+.45*(1-r));roca.userData.recurso={piedra:3};roca.userData.tipo='piedra';chunk.objetos.push(roca);chunk.grupo.add(roca);}
generar(cx,cz){const clave=`${cx},${cz}`;if(this.chunks.has(clave))return;const chunk={grupo:new THREE.Group(),objetos:[],bloques:[]},size=this.tam,verts=[],indices=[],colors=[];
for(let x=0;x<=size;x++)for(let z=0;z<=size;z++){const wx=cx*size+x,wz=cz*size+z,h=this.altura(wx,wz),t=this.tipoBloque(h),y=t==='agua'?this.nivelAgua+.01:h;verts.push(wx,y,wz);const n=this.ruidoSuave(wx*1.7,wz*1.7),detail=(n-.5)*.18;let c=t==='agua'?[.03,.28,.78]:t==='arena'?[.78,.59,.25]:t==='cesped'?[.12,.46,.12]:t==='tierra'?[.34,.19,.08]:[.30,.32,.35];colors.push(...c.map(v=>Math.max(0,Math.min(1,v+detail))));}
for(let x=0;x<size;x++)for(let z=0;z<size;z++){const a=x*(size+1)+z,b=(x+1)*(size+1)+z,c=b+1,d=a+1;indices.push(a,b,d,b,c,d);chunk.bloques.push({x:cx*size+x,z:cz*size+z,tipo:this.tipoBloque(this.altura(cx*size+x,cz*size+z)),destruido:false});}
const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.setIndex(indices);geo.computeVertexNormals();const mat=new THREE.MeshPhongMaterial({vertexColors:true,side:THREE.DoubleSide,shininess:12});const terreno=new THREE.Mesh(geo,mat);terreno.userData.interactivo=true;terreno.userData.bloques=chunk.bloques;chunk.grupo.add(terreno);
for(let x=1;x<size;x++)for(let z=1;z<size;z++){const wx=cx*size+x,wz=cz*size+z,h=this.altura(wx,wz),t=this.tipoBloque(h),r=this.ruidoSuave(wx,wz);if(t==='cesped'&&r<.04)this.crearArbol(wx,wz,h,chunk);if(t!=='agua'&&r<.045)this.crearRoca(wx,wz,h,chunk);}
this.chunks.set(clave,chunk);this.m.escena.add(chunk.grupo);}
actualizarAgua(dt){this.tiempoAgua+=dt;}
eliminarLejanos(cx,cz){for(const [clave,chunk] of this.chunks){const p=clave.split(','),x=parseInt(p[0]),z=parseInt(p[1]),d=Math.max(Math.abs(cx-x),Math.abs(cz-z));if(d>this.radioEliminar){chunk.grupo.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose();}});this.m.escena.remove(chunk.grupo);this.chunks.delete(clave);}}}
actualizar(jx,jz){const cx=Math.floor(jx/this.tam),cz=Math.floor(jz/this.tam);for(let x=-this.radioCarga;x<=this.radioCarga;x++)for(let z=-this.radioCarga;z<=this.radioCarga;z++)this.generar(cx+x,cz+z);this.eliminarLejanos(cx,cz);this.actualizarAgua(.016);}
nuevaSemilla(){for(const chunk of this.chunks.values()){this.m.escena.remove(chunk.grupo);}this.chunks.clear();this.seed=Math.random()*100000;}
}
window.Mundo=Mundo;
