class Mundo {
constructor(m){this.m=m;this.chunks=new Map();this.tam=16;this.radioCarga=3;this.radioEliminar=4;this.seed=Math.random()*100000;}
ruidoSuave(x,z){const n=Math.sin((x*127.1+z*311.7+this.seed)*12.9898)*43758.5453;return n-Math.floor(n);}
altura(x,z){const s=this.seed;const base=ruido(x*.018+s,z*.018+s)*10;const detalle=ruido(x*.055+s*.3,z*.055+s*.3)*3;const mont=Math.pow(Math.max(0,ruido(x*.009+s*.7,z*.009+s*.7)-.42),1.7)*30;return base*.35+detalle*.2+mont-3;}
tipoBloque(h){if(h<0)return'agua';if(h<.8)return'arena';if(h<8)return'cesped';if(h<13)return'tierra';return'piedra';}
crearArbol(x,z,h,chunk){const arbol=new THREE.Group(),tronco=new THREE.Mesh(new THREE.CylinderGeometry(.42,.55,4.5,8),new THREE.MeshLambertMaterial({color:0x92400e})),hojas=new THREE.Mesh(new THREE.SphereGeometry(2.1,10,8),new THREE.MeshLambertMaterial({color:0x15803d}));tronco.position.y=2.25;hojas.position.y=5.1;arbol.add(tronco,hojas);arbol.position.set(x,h,z);arbol.userData.recurso={madera:3,palo:1};tronco.userData.recurso=arbol.userData.recurso;hojas.userData.recurso=arbol.userData.recurso;this.m.escena.add(arbol);chunk.objetos.push(arbol);}
crearRoca(x,z,h,chunk){const roca=new THREE.Mesh(new THREE.DodecahedronGeometry(.7),new THREE.MeshLambertMaterial({color:0x6b7280}));roca.position.set(x,h+.5,z);roca.userData.recurso={piedra:3};this.m.escena.add(roca);chunk.objetos.push(roca);}
generar(cx,cz){const clave=`${cx},${cz}`;if(this.chunks.has(clave))return;const chunk={grupo:new THREE.Group(),objetos:[]},size=this.tam,verts=[],indices=[],colors=[];for(let x=0;x<=size;x++)for(let z=0;z<=size;z++){const wx=cx*size+x,wz=cz*size+z,h=this.altura(wx,wz);verts.push(wx,h,wz);const t=this.tipoBloque(h),c=t==='agua'?[.08,.3,.8]:t==='arena'?[.9,.72,.35]:t==='cesped'?[.18,.62,.2]:t==='tierra'?[.45,.24,.1]:[.38,.4,.43];colors.push(...c);}for(let x=0;x<size;x++)for(let z=0;z<size;z++){const a=x*(size+1)+z,b=(x+1)*(size+1)+z,c=b+1,d=a+1;indices.push(a,b,d,b,c,d);}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.setIndex(indices);geo.computeVertexNormals();chunk.grupo.add(new THREE.Mesh(geo,new THREE.MeshLambertMaterial({vertexColors:true,side:THREE.DoubleSide})));
for(let x=1;x<size;x++)for(let z=1;z<size;z++){const wx=cx*size+x,wz=cz*size+z,h=this.altura(wx,wz),t=this.tipoBloque(h);if(t==='cesped'&&this.ruidoSuave(wx,wz)<.035)this.crearArbol(wx,wz,h,chunk);else if(t==='piedra'&&this.ruidoSuave(wx*2,wz*2)<.025)this.crearRoca(wx,wz,h,chunk);}this.chunks.set(clave,chunk);this.m.escena.add(chunk.grupo);}
eliminarLejanos(cx,cz){for(const [clave,chunk] of this.chunks){const p=clave.split(','),x=parseInt(p[0]),z=parseInt(p[1]),d=Math.max(Math.abs(cx-x),Math.abs(cz-z));if(d>this.radioEliminar){chunk.objetos.forEach(o=>this.m.escena.remove(o));this.m.escena.remove(chunk.grupo);chunk.grupo.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material)o.material.dispose();});this.chunks.delete(clave);}}}
actualizar(jx,jz){const cx=Math.floor(jx/this.tam),cz=Math.floor(jz/this.tam);for(let x=-this.radioCarga;x<=this.radioCarga;x++)for(let z=-this.radioCarga;z<=this.radioCarga;z++)this.generar(cx+x,cz+z);this.eliminarLejanos(cx,cz);}
nuevaSemilla(){for(const chunk of this.chunks.values()){chunk.objetos.forEach(o=>this.m.escena.remove(o));this.m.escena.remove(chunk.grupo);}this.chunks.clear();this.seed=Math.random()*100000;}
}
window.Mundo=Mundo;
